- name: check apt last update
  stat: path=/var/cache/apt
  register: apt_cache_stat

- name: update apt if needed
  apt: update_cache=yes
  when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12
  
- name: install apache2
  apt: pkg={{item}} state=latest
  with_items:
    - apache2
    - php5
    - libapache2-mod-php5
  notify:
  - start apache2
  
- name: start apache2
  action: service name=apache2 state=started
