
- name: Set apache2 proxy to be able to connect via {{source_url}}
  template: src=proxy.conf dest=/etc/apache2/sites-available/{{service_name}}.conf
- shell: a2enmod proxy
- shell: a2enmod proxy_http
- shell: a2enmod rewrite
- shell: a2ensite {{service_name}}
- name: restart apache2
  action: service name=apache2 state=restarted
