
#- name: Add multiverse
#  shell: add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"

- name: check apt last update
  stat: path=/var/cache/apt
  register: apt_cache_stat

- name: update apt if needed
  apt: update_cache=yes
  when: ansible_date_time.epoch|float - apt_cache_stat.stat.mtime > 60*60*12

- name: install complementary packages
  apt: pkg={{ item }}
  with_items:
    - vim
    - tree
    - expect
    - zip

- name: config .vimrc
  copy: src=vimrc dest=/etc/vim/vimrc
  
- name: config .bashrc
  copy: src=bashrc dest=/etc/bash.bashrc
  
# Timezone setting
- name: Set timezone to Seoul/Korea
  shell: ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

- name: Add doroci test servers to the hosts file
  lineinfile: dest=/etc/hosts
              regexp="doroci-test"
              line="10.0.16.159    doroci-test"
              state=present

- name: Add doroci dev servers to the hosts file
  lineinfile: dest=/etc/hosts
              regexp="doroci-dev"
              line="10.0.14.203    doroci-dev"
              state=present
