set nocompatible
set autoindent
set cindent
set smartindent
set textwidth=79
set wrap
set nowrapscan
set nobackup
set visualbell
set ruler
set tabstop=4
set shiftwidth=4
set backspace=2

if $LANG[0] == 'k' && $LANG[1] == 'o'
set fileencoding=korea
endif

if &term =~ "xterm-debian" || &term =~ "xterm-xfree86"
set t_Co=16
set t_Sf=^[[3%dm
set t_Sb=^[[4%dm
set t_kb=^H
fixdel
endif

if has("syntax")

syntax on " Default to no syntax highlightning 
endif
