---

- name: analyzer_runner | Download
  get_url:
    url="{{sonar_analyzer_runner_url}}"
    dest="/tmp/{{sonar_analyzer_runner_file}}"
  tags: analyzer_runner

- name: analyzer_runner | Create base dir
  file:
    dest="{{sonar_analyzer_runner_dir}}"
    state=directory
  tags: analyzer_runner

- name: analyzer_runner | Extract archive
  unarchive:
    src="/tmp/{{sonar_analyzer_runner_file}}"
    dest="{{sonar_base_dir}}/"
    copy=no
    creates="{{sonar_analyzer_runner_dir}}/conf"
  tags: analyzer_runner

- name: analyzer_runner | Configuration file
  template:
    src=sonar-runner.properties.j2
    dest="{{sonar_analyzer_runner_dir}}/conf/sonar-runner.properties"
  tags: analyzer_runner

- name: make link
  file: src={{sonar_analyzer_runner_dir}} dest={{sonar_analyzer_runner_dir_link}} state=link

- name: analyzer_runner | bash profile SONAR_RUNNER_HOME
  lineinfile:
     dest="/etc/bash.bashrc"
     state=present
     create=yes
     regexp="SONAR_RUNNER_HOME"
     line="export SONAR_RUNNER_HOME={{sonar_analyzer_runner_dir_link}}"
  tags: analyzer_runner

- name: analyzer_runner | bash profile PATH
  lineinfile:
     dest="/etc/bash.bashrc"
     state=present
     create=yes
     regexp="{{sonar_base_dir}}"
     line="export PATH=$PATH:{{sonar_analyzer_runner_dir_link}}/bin"
  tags: analyzer_runner

