
ansible_done_dir: /etc/ansible/.done
ldap_done_dir: '{{ ansible_done_dir }}/ldap'
ldap_create_user_and_groups_done: '{{ ldap_done_dir }}/create-users-and-groups'
ldap_create_indexes_done: '{{ ldap_done_dir }}/create-indexes'
ldap_create_autofs_done: '{{ ldap_done_dir }}/create-autofs'
ldap_create_automount_done: '{{ ldap_done_dir }}/create-automount'
ldap_create_sudo_done: '{{ ldap_done_dir }}/create-sudo'
ldap_create_sudo_master_done: '{{ ldap_done_dir }}/create-sudo-master'
ldap_slapd_dpkg_reconfigure_done: '{{ ldap_done_dir }}/slapd-dpkg-reconfigure-done'

ldap_host: example.com
ldap_dc: dc=example,dc=com
ldap_password: humax@!
ldap_password_size: 7  # The length ldap_password
ldap_automount_machine: nfs.example.com
ldap_server: ldap://ldap.example.com
ldap_g_suffix: ou=Groups
ldap_u_suffix: ou=Users
ldap_m_suffix: ou=Machines

ldap_include_create_user_and_groups: True
ldap_include_create_indexes: True
ldap_include_create_autofs: True
ldap_include_create_automount: True
ldap_include_create_sudo: True
ldap_include_create_sudo_master: True
